Pod::Spec.new do |s|
  s.name                    = 'MagniteSDK'
  s.version                 = '1.0.2'
  s.summary                 = 'Magnite SDK for mobile advertising'

  s.description             = <<-DESC
                              'Magnite In-App Ads enables you to reap the benefits of Magnite's In-App monetization products, which maximize the revenue generated by your application. All this profit-making is achieved with minimal effort and minimal interference with your users’ experience.'
                                DESC
                       
  s.platform                = :ios
  s.ios.deployment_target   = '12.0'
  s.homepage                = 'https://www.magnite.com/'
  s.license                 = { :type => 'Commercial', :file => 'LICENSE.md' }
  s.author                  = { 'Magnite' => 'sdk@magnite.com' }
  s.source                  = { :git => 'https://github.com/MagniteEngineering/ios-sdk-pod.git', :tag => s.version.to_s }
  
  s.ios.vendored_frameworks = 'MagniteSDK.xcframework'
  s.frameworks              =
                            'AdSupport',
                            'AppTrackingTransparency',
                            'AVFoundation',
                            'CoreAudio',
                            'CoreFoundation',
                            'CoreGraphics',
                            'CoreMedia',
                            'CoreTelephony',
                            'Foundation',
                            'JavaScriptCore',
                            'NetworkExtension',
                            'QuartzCore',
                            'StoreKit',
                            'SystemConfiguration',
                            'UIKit',
                            'WebKit'
  s.libraries               = 'z'

end
